### ISSUE TITLE
Identifying group II introns in gymnosperm mitochondria

### ISSUE THREAD

**Issue by sjackman** [EddyRivasLab/infernal#15]
I'm using Infernal and RFAM to identify group II introns in gymnosperm mitochondria. Using `cmscan --mid --cut_ga --nohmmonly` it identifies 8 out of 16 family Intron_gpII ([RF00029](http://rfam.org/family/RF00029)). Using the Infernal CM for Domain-V ([RM00007](http://rfam.xfam.org/motif/RM00007)) it's able to identify all 16 introns, which is great! Could an RFAM family be constructed from this motif?

I see that no gymnosperm mitochondria are present in sequences of RF00029, which may be the cause of the lack of sensitivity that I observed. Could the mitochondrial genomes of *Cycas taitungensis* NC_010303.1, *Ginkgo biloba* NC_027976.1, *Welwitschia mirabilis* NC_029130.1, and *Picea glauca* LKAM01.1 be added to the Intron_gpII (RF00029) family?

I found no hits at all to clan group-II-D1D4 ([CL00102](http://rfam.xfam.org/clan/CL00102)) in my gymnosperm mitochondrial genomes. Could a new family be added to this clan constructed from plant mitochondrial genomes, including gymnsoperms?

Thank you for Infernal and RFAM! When cmscan is able to find a match to Intron_gpII, it is often is able to identify the exact 3' splice site of the intron, which is not always straight forward by eye.

**Comment by nawrockie** [comment]
Thanks for your comments. Your questions are more about Rfam than Infernal, could you please also send an email to rfam-help@ebi.ac.uk? They can address your questions about modifying and adding new models. (I also work with Rfam but am not the most relevant person to answer those questions.) 

Regarding your use of cmscan, have you tried --nohmm or --max instead of --mid? Those options will take longer but should be more sensitive. The most sensitive is --max, but it is also the slowest. If running time is really an issue, you might try to first identify hits using the RM00007 motif, expand those hit regions into larger windows that should include the full intron, and then run cmscan using the Rfam models in CL00102 and --nohmm or --max on those windows. 

Also, have you considered building your own models from your mitochondrial hits, and then searching for more mitochondrial introns with those models? One quick way to do this is to collect your hits into a fasta file (hits.fa), then run 'cmalign -o hits.stk RF00029.cm hits.fa', and then 'cmbuild --refine -o hits.cmbuild.stk hits.cm hits.stk'. The --refine option to cmbuild can improve the hits.stk alignment prior to building the model. You will then need to calibrate the model to use it with cmscan/cmsearch.

**Comment by sjackman** [comment]
Thanks for your quick reply, Eric.

> Your questions are more about Rfam than Infernal, could you please also send an email to rfam-help@ebi.ac.uk?

👍 Will do.

> Regarding your use of cmscan, have you tried --nohmm or --max instead of --mid?

Searching all of RFAM with `--nohmm` or `--max` was way too slow (~2 hours so far for `--nohmm` on 25 kbp with 48 threads). I downloaded the CM for only Intron_gpII (RF00029), and that's fast enough (33 s for `--nohmm` and 3 minutes for `--max`). With `--mid` it identified 8 of 16, and with `--nohmm` and `--max` it identified 9 of 16. I'd also like to apply this to the entire ~5 Mbp genome, not only the introns.

> Also, have you considered building your own models from your mitochondrial hits, and then searching for more mitochondrial introns with those models?

No, but I'm trying that now.

> You will then need to calibrate the model to use it with cmscan/cmsearch.

`cmcalibrate --cpu=48 --seed=1 groupII-DV-VI.cm`

Could you please add a `-o` option to specify the output path? (by default foo.c.cm)

**Comment by sjackman** [comment]
> Also, have you considered building your own models from your mitochondrial hits, and then searching for more mitochondrial introns with those models?

Building a model from the 9 hits of `--mid --cut_ga`, and then using `cmscan --mid` with that model matched 10 of 16 introns, not as effective as I was hoping. Perhaps 9 sequences is too few. I may have better luck including sequences from other related species.

It seems that `--cut_ga` (40 for RF00029) is overly restrictive for my particular purpose. Here are the 16 scores reported by `cmscan --max` with the RF00029 model:

| Bit score | E score |
|----------:|--------:|
|      66.6 | 2.1e-16 |
|      64.0 | 8.6e-16 |
|      62.2 | 3.7e-15 |
|      51.4 | 9.8e-13 |
|      49.5 | 2.3e-12 |
|      48.9 | 9.8e-12 |
|      48.0 | 7.3e-12 |
|      47.0 | 3.3e-11 |
|      42.5 | 4.4e-10 |
|      38.7 | 2.2e-09 |
|      38.5 | 5.0e-09 |
|      38.1 | 2.2e-09 |
|      37.6 | 8.2e-09 |
|      34.2 | 3.5e-08 |
|      29.0 | 1.8e-07 |
|      21.8 | 3.1e-05 |

Reducing the score threshold from 40 to `--incT=30` would get 14 of 16, and reducing it to `--incT=20` would get all 16 of 16. Either `cmscan --mid --incT=20` or `cmscan --mid --incE=1e-4` finds all 16 hits.

These above E scores are when limiting the search to the sequence of the 16 known introns. Ultimately my goal is to apply this search to the entire 5 Mbp genome, to identify novel introns. The two worst hits with bit scores 29.0 and 21.8 have E scores of 3.6e-5 and 0.035 respectively when searching the whole genome.

Building a model from the 16 hits of `--mid --incT=20`, and then using `cmscan --mid` with that model matched 14 of 16 introns with `--mid --incT=40`, and 15 out of 16 introns with `--mid --incE=0.01`. That's a good result. Oddly it loses one match which had a good hit with RF00029, bit score of 47 and E score of 3.3e-11, with this newly created model has a bit score of 7.4 and E score 0.16.

Most of the above rambling is really just a brain dump for me to organize my own thoughts, and perhaps be useful to a future reader (or my future self when I inevitably Google it a year from now). What I've learnt is…
- creating a custom `.cm` of just the models you're interested in is much faster than searching all of RFAM
- adjust `--incT` to a threshold that includes your known good hits
- building a custom model is fun and seems to usually improve bit scores of matches

**Comment by nawrockie** [comment]
You've realized something very important that I failed to bring up in my first comment: the choice of score threshold is crucial, especially for your application. You used --cut_ga, which is recommended when annotating genomes/datasets because it enforces that only scores above the manually defined Rfam score X threshold are reported. This means an Rfam curator looked at results in a large search and decided that there were zero false positives with a score of X or above. That's appropriate if you're annotating many genomes/datasets with a library of CMs in an automated fashion where avoiding false positives is paramount and you're not going to examine the results. But your case is different. You're looking in detail at a single family and trying to find all hits in a relatively small database. In this case I don't recommend using --cut_ga. What you should do is look at all hits down to a score that starts including the first few false positives. This will let you know where the score threshold is that you should use for this search. If you run cmsearch by default, then the score threshold is set as an E-value of 10, and this should get you at least a few false positives. (By the way, you should probably be using cmsearch and not cmscan for your application, where you are just using a single model, for reasons related to the difference in how E-values are calculated by those two programs explained in the user guide.) If, when using an E-value threshold of 10 you find that all hits look real to you (you might examine them by running the motif model you mentioned against all of them as a test), then you want to lower that threshold until you do start seeing false positives.  The worst E-value of 0.035 for your 16 trusted group I introns is still significant, and makes me think that maybe there are more than 16 introns -- are there any with worse E-values that you've convinced yourself are false positives? Running with --nohmm and --max will return more hits with E-values near 1, so it will enable you to more precisely determine where the boundary is between false positives and true positives. Also, it is certainly possible you will have some true positives below your first false positive. If you really want to find all the introns, you should look at as many of the marginal E-value hits as possible (as many as you are willing to) until you convince yourself there are no more real ones left that you are going to be able to find in the cmsearch results. If you find any ones you think are real with worse scores than the first false positive, you can then include them in a new seed alignment, build a new CM, and their scores may then rise above all false positives with that new model.

Another idea apart from building your own model is to add your candidate sequences to the RF00029 seed alignment and build a model from that combined seed. This may help alleviate the issue that you had a single sequence drop its score from RF00029 to your new model, which, I agree, is a little surprising. This probably means that that particular intron is more similar to a larger number of sequences in the RF00029 seed alignment than it is to the other introns in your new seed alignment. 

Finally, on the problem of speed for the --max and --nohmm models on your 5Mb search. Running for more than 2 hours does not seem to be a deal breaker to me, but if you plan to do searches in much larger datasets then I can understand your concern. One thing you did not comment on was my idea to run the motif model first, since you said it was so sensitive, and then fetch out windows surrounding those hits into a new fasta file, and running the full intron models on those with --max or --nohmm. That requires more work by you, but may be a more sensitive method that runs in a an acceptable amount of time.

**Comment by sjackman** [comment]
Wow. Thank you very much for the lengthy response, and on a Saturday.

> By the way, you should probably be using cmsearch and not cmscan for your application, where you are just using a single model, for reasons related to the difference in how E-values are calculated by those two programs explained in the user guide.

Thank you for the tip!

> The worst E-value of 0.035 for your 16 trusted group I introns is still significant, and makes me think that maybe there are more than 16 introns

Both cis-splicing and trans-splicing are common in mitochondrial genomes. This genome has 29 known introns. 16 introns are cis-spliced and compose my trusted set. The 13 trans-spliced introns are also trusted, but are disrupted in the genome, so that the intron now occurs in two pieces separated in the genome. Complementary sequence in a stem allow them to find each other after transcription and form the correct secondary structure. The disruption usually occurs in somewhere in domain 1 through 4, most typical is in the loop of domain 4. I have one example where I believe the disruption occurs in domain 5. RM00007 covers domain 5. RF00029 covers domains 5 and 6.

> are there any with worse E-values that you've convinced yourself are false positives?

This is a tricky question for me to answer. There's pseudogenes and fragments of introns in the genome, so there are cases that may be a true positive, but have no evident nearby coding sequence. It may be a true example of this family, but may not be functional.

There are 35 hits of RF00029 to the whole genome with `cmscan --mid --incT=20`. Only one has a worse score than the trusted hit with a bit score of 21.8 and E score 0.035, and it has a bit score of 21.5 and E score of 0.042. It may be a real example of this family, but it does not appear to be functional, as far as I can tell. The downstream sequence has no homology to proteins in nr using blastx. There are 14 more hits with bit scores between 10 and 20, twelve of these hits' E scores exceed 1.

> Another idea apart from building your own model is to add your candidate sequences to the RF00029 seed alignment and build a model from that combined seed.

I like this idea. I found http://rfam.xfam.org/family/RF00029#tabview=tab2 to download the seed alignments of RF00029. Which tool do I use to combine the seed alignments of RF00029 with my hits aligned with `cmalign`?

> One thing you did not comment on was my idea to run the motif model first, since you said it was so sensitive, and then fetch out windows surrounding those hits into a new fasta file, and running the full intron models on those with --max or --nohmm. That requires more work by you, but may be a more sensitive method that runs in a an acceptable amount of time.

A related option to add the 16 trans-spliced introns to the model is to identify their domain 5 using RM00007, extract the sequence from RM00007 to the 3' splice site identified using BLAST and homologous proteins (this region should include only domain V and VI), align those sequences using `cmalign` and RF00029, and build a model composed of the seeds of RF00029 and these additional sequences. I could potentially extend this approach to three related species to add additional sequences to the model.

**Comment by sjackman** [comment]
> Only one has a worse score than the trusted hit with a bit score of 21.8 and E score 0.035, and it has a bit score of 21.5 and E score of 0.042. It may be a real example of this family, but it does not appear to be functional, as far as I can tell. The downstream sequence has no homology to proteins in nr using blastx.

I just noticed that this hit to RF00029 has no hit to the usually more sensitive RM00007, so this case may be a false positive, or a non-functional example of the family.

**Comment by sjackman** [comment]
> Finally, on the problem of speed for the --max and --nohmm models on your 5Mb search. Running for more than 2 hours does not seem to be a deal breaker to me, but if you plan to do searches in much larger datasets then I can understand your concern.

Two hours is fast enough to run on my two species plus the 4 gymnosperm mitochondria in RefSeq. It'd need to be faster to expand my search to the 222 plant mitochondria in RefSeq.

**Comment by nawrockie** [comment]
> I like this idea. I found http://rfam.xfam.org/family/RF00029#tabview=tab2 to download the seed alignments of RF00029. Which tool do I use to combine the seed alignments of RF00029 with my hits aligned with cmalign?

You can combine two stockholm alignments that have the same RF annotation (so two alignments created by cmalign to the same model, or a cmalign alignment to a CM and the Rfam downloaded seed alignment for that same CM should work too) using the esl-alimerge executable easel 'miniapp' in infernal-1.1.2/easel/miniapps/ after installing infernal. 

A few more thoughts:

- when searching with the motif model, you might be able to get away with --max because the model is so small, and the empirical runtime complexity of the --max algorithm is N^3logN, so it's way slower on longer models than shorter ones. 

- there's yet another expert option in cmsearch that might be helpful to you: --anytrunc. This allows hits that are truncated in the middle of the model to get reported. By default only truncated hits that are truncated due to the end of the sequence are reported. For the trans splicing introns, --anytrunc should be better suited to finding partial hits. 

- you may already be thinking this, but you might want to iterate the model building/search process you are doing for the 4 gymnosperm mito genomes when you expand to the larger search space of the 222 plant mito genomes. You can use --mid to pick up what hits you can find, then add them into your growing seed alignment, rebuild the model and redo the search with --mid. That new search may then find additional hits missed in the previous round (some of which may have been found with --max, but that's too slow to be practical). You can repeat this strategy until no new hits are found. At each stage, you can remove highly identical sequences (if any) from the seed using the 'esl-weight' easel miniapp, like this: 'esl-weight -f --idf 0.96 <alignment file>' to remove sequences that are 96% identical. This iterative technique is a good strategy for building a model.
