### ISSUE TITLE
Report: cmalign --small options error message is truncated ?

### ISSUE THREAD

**Issue by persalteas** [EddyRivasLab/infernal#20]
Hello,

When using cmalign with option --small, it looks like several other options are mandatory.
But the error message is truncated:

> Failed to parse command line: Option --small requires (or has no effect without) option(s) --cyk,--noprob,--nonband
> Usage: cmalign [-options] <cmfile> <seqfile>
> 
> where basic options are:
>   -h     : show brief help on version and usage
>   -o <f> : output the alignment to file <f>, not stdout
>   -g     : configure CM for global alignment [default: local]
> 
> To see more help on available options, do cmalign -h

It seems that in addition to the three options mentionned, we need to use --notrunc to correctly launch cmalign. I wish the error message was complete: _Option --small requires (or has no effect without) option(s) --cyk,--noprob,--nonbanded **and --notrunc**_

Steps to reproduce:

- launch cmalign with options --small, --cyk, --noprob and --nonband: `cmalign --small --cyk --noprob --nonband yourfile.cm yourfile.fa`

This was just a small report.
Thank you,

Louis

**Comment by nawrockie** [comment]
Hi Louis, 

Thanks for reporting this and sorry for the very slow response. This is due to specifics of the implementation that limit the length of that error message and are actually difficult to change. I will update the user guide and man pages to include the full list of options that are incompatible with `cmalign --small` for the next release.
