### ISSUE TITLE
How to hide command line pipeline statistics summaries?

### ISSUE THREAD

**Issue by glickmac** [EddyRivasLab/infernal#23]
Hello,

I am running cmscan --rfam against a large dataset and the program itself is very fast, however I am worried the print statements to the command line are creating lag in the wall time of the program. **Is there a flag to hide the Internal CM pipeline statistics summary printout after each sequence?** ```Infernal Version 1.1.3```

Example of command line printout after each sequence I want to remove:
```
Query:       B_NZ_CP042170-NZ-CP042170_2305641;aligned_75_F_84_20400_0  [L=20496]
Hit scores:
 rank     E-value  score  bias  modelname          start    end   mdl trunc   gc  description
 ----   --------- ------ -----  ----------------- ------ ------   --- ----- ----  -----------
  (1) !         0 2766.8  37.1  LSU_rRNA_bacteria  11664  14547 +  cm    no 0.49  Bacterial large subunit ribosomal RNA
  (2) !         0 1527.8   3.2  SSU_rRNA_bacteria   9586  11099 +  cm    no 0.50  Bacterial small subunit ribosomal RNA


Internal CM pipeline statistics summary:
----------------------------------------
Query sequence(s):                                               1  (40992 residues searched)
Query sequences re-searched for truncated hits:                  1  (11514.0 residues re-searched, avg per model)
Target model(s):                                                 2  (4458 consensus positions)
Windows   passing  local HMM SSV           filter:               4  (0.1216); expected (0.06)
Windows   passing  local HMM Viterbi       filter:               2  (0.07802); expected (0.02)
Windows   passing  local HMM Viterbi  bias filter:               2  (0.07802); expected (0.02)
Windows   passing  local HMM Forward       filter:               2  (0.07802); expected (0.0002)
Windows   passing  local HMM Forward  bias filter:               2  (0.07802); expected (0.0002)
Windows   passing glocal HMM Forward       filter:               2  (0.07802); expected (0.0002)
Windows   passing glocal HMM Forward  bias filter:               2  (0.07802); expected (0.0002)
Envelopes passing glocal HMM envelope defn filter:               2  (0.0421); expected (0.0002)
Envelopes passing  local CM  CYK           filter:               2  (0.04203); expected (0.0001)
Total CM hits reported:                                          2  (0.04188); includes 0 truncated hit(s)

# CPU time: 5.23u 0.49s 00:00:05.72 Elapsed: 00:00:04.48
```
My command:
```cmscan --tblout Output.txt --rfam Models.cm Metag_seqs.fasta```

**Comment by nawrockie** [comment]
Unfortunately, no. My only suggestion to try is piping stdout to /dev/null and using the results in the --tblout output file.

For the example you provided, I'd be surprised if the printing of the pipeline stats was a significant amount of the run time because that sequence took about 5s. If the sequences were really short than the printing of those stats would take longer relative to the total running time, but I would still doubt that it was significant. (But I could be wrong.)

An alternative is to run cmsearch, instead of cmscan, which will output the results per-model instead of per-sequence. It may be faster for large sequence sets, and there are only two differences: 

(1) the order of the output is arranged per-model instead of per-sequence, but you can always sort the --tblout output after running if you'd like
(2) E-values will be different, for more details on this see page 25 of the infernal 1.1.3 user guide (part of step 3 of the tutorial).

**Comment by npcarter** [comment]
Another thought is that writing output to a file is typically much faster
than displaying it on a terminal, so if you need the full output of
cmsearch, you could try that redirection instead of Sean's /dev/null
suggestion.

**Comment by nawrockie** [comment]
Thanks, Nick. That's a great point!

**Comment by glickmac** [comment]
Thanks @nawrockie and @npcarter, I will try the suggestion to print to a file. Many of these sequence, I am running against are short (< 750bps) so printing to the terminal seemed too time consuming per sequence. I will close this issue.
