### ISSUE TITLE
time complexity of cmsearch

### ISSUE THREAD

**Issue by kad-ecoli** [EddyRivasLab/infernal#25]
I wonder how to calculate the complexity of cmsearch. I originally thought that to search a query covariance model with L1 positions through a database of M sequences, with average length of L2, the time complexity should be around O(L1*M*L2). However, this does not seem to be the case. In the attached example, the query covariance model has 307 positions, and the sequence database is only 32M. cmsearch (INFERNAL 1.1.3, 64 bit Linux) has been running for more than 2 days, but has not yet finished:

```bash
cmsearch --noali -A cmsearch.a2m --cpu 2 seq.cm seq.db
```

[input.zip](https://github.com/EddyRivasLab/infernal/files/5939417/input.zip)

**Comment by kad-ecoli** [comment]
Here is the split sequence database:

```bash
zcat xa*.gz > seq.db
```
[xaa.gz](https://github.com/EddyRivasLab/infernal/files/5939432/xaa.gz)
[xab.gz](https://github.com/EddyRivasLab/infernal/files/5939433/xab.gz)
[xac.gz](https://github.com/EddyRivasLab/infernal/files/5939434/xac.gz)
[xad.gz](https://github.com/EddyRivasLab/infernal/files/5939435/xad.gz)

**Comment by nawrockie** [comment]
The dynamic programming algorithm that cmsearch implements is actually O(LN^3) with L being the database size (M*L2 in your terms) and N being the length of the query model (see https://pubmed.ncbi.nlm.nih.gov/17397253/), but empirically it is faster due to heuristics including profile HMM filters (see section 4 of the infernal user's guide (http://eddylab.org/infernal/Userguide.pdf)) which themselves have the time complexity of O(L1ML2) in your terms. The actual running time depends on a lot of factors including composition of the database. It looks like your database has a high fraction of real structural RNAs (as opposed to random nonhomologous sequences) which increases running time because a high fraction of these will survive the filters and be analyzed with the more expensive CM algorithms

I ran your CM file against a random 1% of your database (which is 32 Mb gzipped but 350 million nucleotides) and found that with your option settings, cmsearch took 35 minutes meaning that on my hardware your full cmsearch run should take about 60 hours. So I'm not surprised your search is still running. It should finish in the next day or so.

**Comment by kad-ecoli** [comment]
This make a lot of sense.

I have another question. Is there a way to tell cmsearch to output up to N alignments in the -o and -A output files. Essentially, I am looking for infernal options equivalent to the -max_target_seqs and/or -num_alignments options of blastn. I have several cases where cmsearch output is so large that it crash the local disk space:

**Comment by nawrockie** [comment]
There is no equivalent to -max_target_seqs or -num_alignments, all alignments are always output.

One suggestion is to use the `--tblout <f>` file (along with your other cmsearch options) to save tabular output of all hits to `<f>`, then using `esl-sfetch` to fetch out the hits and `cmalign` to align them to a CM as described in the section "Identify examples of a single RNA family in a sequence dataset using cmsearch" on page 10 of this publication:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6754622/

Note that you can also remove some hits from the `--tblout <f>` file before fetching them, if you don't want to align all of them.

**Comment by kad-ecoli** [comment]
Yes, fetching hits from --tblout (or from -o) indeed works. Thank you.
