### ISSUE TITLE
Unmasked or masked input genome

### ISSUE THREAD

**Issue by StevenBai97** [EddyRivasLab/infernal#26]
Hello,
Which kind of genome.fasta could be the input file of cmscan? Unmasked genome, softmasked or hardmasked one?

**Comment by nawrockie** [comment]
cmscan will accept any of those 3 kinds of fasta files. The results will be identical for an unmasked and softmasked file (assuming your definition of softmasked is masked nucleotides are marked as lowercase) because cmscan treats uppercase and lowercase nucleotides identically. The results could be different for a hardmasked file depending on which regions are masked. Some common eukaryotic repeat sequences (e.g. Alu elements in primate genomes) derive from structural RNAs and so masking those out may reduce the number of (potentially unwanted) hits to certain Rfam models.

**Comment by StevenBai97** [comment]
> cmscan will accept any of those 3 kinds of fasta files. The results will be identical for an unmasked and softmasked file (assuming your definition of softmasked is masked nucleotides are marked as lowercase) because cmscan treats uppercase and lowercase nucleotides identically. The results could be different for a hardmasked file depending on which regions are masked. Some common eukaryotic repeat sequences (e.g. Alu elements in primate genomes) derive from structural RNAs and so masking those out may reduce the number of (potentially unwanted) hits to certain Rfam models.

Thank you very much!
