### ISSUE TITLE
cmpress fails without useful information when .cm file contains 2 models with identical NAME

### ISSUE THREAD

**Issue by qifei9** [EddyRivasLab/infernal#43]
If a `.cm` file contains multiple models, and some of them have identical `NAME`, `cmpress` will fail as:
```
Working...     %
```
There is no useful information, so it's difficult to address the issue. 

If it could print the model NAME causing the problem, it would be very helpful.

I used version 1.1.4. I have not tried version 1.1.5, but I guess it would be the same, since I see nothing related to `cmpress` in the release note of version 1.1.5

**Comment by nawrockie** [comment]
@qifei9 : try 1.1.5, which gives an error message with information on the duplicated name. I wasn't aware of this problem before you reported it and the relevant change between 1.1.4 and 1.1.5 releases was made in the easel library used by infernal, which is why there is nothing in the release notes about it.
